/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFachadaVeterinario;

/**
 *
 * @author alvanirjunior
 */
public class CadastroVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVeterinario
     */
    public CadastroVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFoneCadastroRecepcionista = new javax.swing.JLabel();
        labelCadastroClient = new javax.swing.JLabel();
        labelNomeCadastroVeterinario = new javax.swing.JLabel();
        textNomeCadastroVeterinario = new javax.swing.JTextField();
        labelSexoCadastroVeterinario = new javax.swing.JLabel();
        checkboxMCadastroVeterinario = new javax.swing.JCheckBox();
        checkboxFCadastroVeterinario = new javax.swing.JCheckBox();
        labelFoneCadastroVeterinario = new javax.swing.JLabel();
        TextFoneCCadastroVeterinario = new javax.swing.JTextField();
        labelDataNcCadastroVeterinario = new javax.swing.JLabel();
        TextFoneCadastroVeterinario = new javax.swing.JTextField();
        labelEnderecoCadastroVeterinario = new javax.swing.JLabel();
        textEnderecoCadastroVeterinario = new javax.swing.JTextField();
        labelLoginCadastroVeterinario = new javax.swing.JLabel();
        TextLoginCadastroVeterinario = new javax.swing.JTextField();
        labelSenhaCadastroVeterinario = new javax.swing.JLabel();
        jPasswordField1CadastroVeterinario = new javax.swing.JPasswordField();
        botaoCadastroVeterinario = new javax.swing.JButton();

        labelFoneCadastroRecepcionista.setText("Fone:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCadastroClient.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        labelCadastroClient.setText("Cadastro Veterinario");

        labelNomeCadastroVeterinario.setText("Nome:");

        textNomeCadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeCadastroVeterinarioActionPerformed(evt);
            }
        });

        labelSexoCadastroVeterinario.setText("Sexo:");

        checkboxMCadastroVeterinario.setText("Masculino");
        checkboxMCadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMCadastroVeterinarioActionPerformed(evt);
            }
        });

        checkboxFCadastroVeterinario.setText("Feminino");

        labelFoneCadastroVeterinario.setText("Fone:");

        TextFoneCCadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFoneCCadastroVeterinarioActionPerformed(evt);
            }
        });

        labelDataNcCadastroVeterinario.setText("Data Nascimento:");

        TextFoneCadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFoneCadastroVeterinarioActionPerformed(evt);
            }
        });

        labelEnderecoCadastroVeterinario.setText("Endereço:");

        textEnderecoCadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnderecoCadastroVeterinarioActionPerformed(evt);
            }
        });

        labelLoginCadastroVeterinario.setText("Login:");

        TextLoginCadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLoginCadastroVeterinarioActionPerformed(evt);
            }
        });

        labelSenhaCadastroVeterinario.setText("Senha:");

        jPasswordField1CadastroVeterinario.setText("jPasswordField1");
        jPasswordField1CadastroVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1CadastroVeterinarioActionPerformed(evt);
            }
        });

        botaoCadastroVeterinario.setText("Cadastrar Veterinario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(112, Short.MAX_VALUE)
                        .addComponent(jPasswordField1CadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(botaoCadastroVeterinario)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelEnderecoCadastroVeterinario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textEnderecoCadastroVeterinario))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDataNcCadastroVeterinario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TextFoneCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCadastroClient)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNomeCadastroVeterinario)
                                            .addComponent(labelSexoCadastroVeterinario)
                                            .addComponent(labelFoneCadastroVeterinario))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkboxMCadastroVeterinario)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkboxFCadastroVeterinario))
                                            .addComponent(textNomeCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TextFoneCCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelLoginCadastroVeterinario)
                                    .addGap(26, 26, 26)
                                    .addComponent(TextLoginCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSenhaCadastroVeterinario)
                                .addGap(236, 236, 236)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroClient)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCadastroVeterinario)
                    .addComponent(textNomeCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexoCadastroVeterinario)
                    .addComponent(checkboxMCadastroVeterinario)
                    .addComponent(checkboxFCadastroVeterinario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFoneCadastroVeterinario)
                    .addComponent(TextFoneCCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNcCadastroVeterinario)
                    .addComponent(TextFoneCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnderecoCadastroVeterinario)
                    .addComponent(textEnderecoCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLoginCadastroVeterinario)
                    .addComponent(TextLoginCadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenhaCadastroVeterinario)
                            .addComponent(jPasswordField1CadastroVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(botaoCadastroVeterinario)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxMCadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMCadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxMCadastroVeterinarioActionPerformed

    private void TextFoneCCadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFoneCCadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFoneCCadastroVeterinarioActionPerformed

    private void TextFoneCadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFoneCadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFoneCadastroVeterinarioActionPerformed

    private void TextLoginCadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLoginCadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLoginCadastroVeterinarioActionPerformed

    private void textEnderecoCadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnderecoCadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnderecoCadastroVeterinarioActionPerformed

    private void textNomeCadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeCadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeCadastroVeterinarioActionPerformed

    private void jPasswordField1CadastroVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1CadastroVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1CadastroVeterinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFoneCCadastroVeterinario;
    private javax.swing.JTextField TextFoneCadastroVeterinario;
    private javax.swing.JTextField TextLoginCadastroVeterinario;
    private javax.swing.JButton botaoCadastroVeterinario;
    private javax.swing.JCheckBox checkboxFCadastroVeterinario;
    private javax.swing.JCheckBox checkboxMCadastroVeterinario;
    private javax.swing.JPasswordField jPasswordField1CadastroVeterinario;
    private javax.swing.JLabel labelCadastroClient;
    private javax.swing.JLabel labelDataNcCadastroVeterinario;
    private javax.swing.JLabel labelEnderecoCadastroVeterinario;
    private javax.swing.JLabel labelFoneCadastroRecepcionista;
    private javax.swing.JLabel labelFoneCadastroVeterinario;
    private javax.swing.JLabel labelLoginCadastroVeterinario;
    private javax.swing.JLabel labelNomeCadastroVeterinario;
    private javax.swing.JLabel labelSenhaCadastroVeterinario;
    private javax.swing.JLabel labelSexoCadastroVeterinario;
    private javax.swing.JTextField textEnderecoCadastroVeterinario;
    private javax.swing.JTextField textNomeCadastroVeterinario;
    // End of variables declaration//GEN-END:variables
}
