/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFachadaRecepcionista;

/**
 *
 * @author alvanirjunior
 */
public class ConsultarCadastroAnimal extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCadastroAnimal
     */
    public ConsultarCadastroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNomeClienteConsultaCadastroAnimal = new javax.swing.JLabel();
        TextNomeClienteConsultaCadastroAnimal = new javax.swing.JTextField();
        labelNcConsultaCadastroAnimal = new javax.swing.JLabel();
        TextDataNcConsultaCadastroAnimal = new javax.swing.JTextField();
        labelConsultaCadastroAnimal = new javax.swing.JLabel();
        textNomeAnimalConsultaCadastroAnimal = new javax.swing.JTextField();
        botaoConsultarCadastroAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Consultar Cadastro Animal");

        labelNomeClienteConsultaCadastroAnimal.setText("Nome do Cliente:");

        labelNcConsultaCadastroAnimal.setText("Data de Nascimento:");

        labelConsultaCadastroAnimal.setText("Nome do Animal:");

        botaoConsultarCadastroAnimal.setText("Consultar Cadastro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelConsultaCadastroAnimal)
                                .addGap(18, 18, 18)
                                .addComponent(textNomeAnimalConsultaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNcConsultaCadastroAnimal)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextDataNcConsultaCadastroAnimal))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNomeClienteConsultaCadastroAnimal)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextNomeClienteConsultaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoConsultarCadastroAnimal)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeClienteConsultaCadastroAnimal)
                    .addComponent(TextNomeClienteConsultaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNcConsultaCadastroAnimal)
                    .addComponent(TextDataNcConsultaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConsultaCadastroAnimal)
                    .addComponent(textNomeAnimalConsultaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(botaoConsultarCadastroAnimal)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCadastroAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDataNcConsultaCadastroAnimal;
    private javax.swing.JTextField TextNomeClienteConsultaCadastroAnimal;
    private javax.swing.JButton botaoConsultarCadastroAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelConsultaCadastroAnimal;
    private javax.swing.JLabel labelNcConsultaCadastroAnimal;
    private javax.swing.JLabel labelNomeClienteConsultaCadastroAnimal;
    private javax.swing.JTextField textNomeAnimalConsultaCadastroAnimal;
    // End of variables declaration//GEN-END:variables
}
