/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFachadaRecepcionista;

/**
 *
 * @author alvanirjunior
 */
public class DesmarcarConsultas extends javax.swing.JFrame {

    /**
     * Creates new form DesmarcarConsultas
     */
    public DesmarcarConsultas() {
        initComponents();
    }

    DesmarcarConsultas(String clique_Aqui) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNomeVetDesmarcarConsultas = new javax.swing.JLabel();
        textNomeVetDesmarcarConsultas = new javax.swing.JTextField();
        labelNomeClienteDesmarcarConsultas = new javax.swing.JLabel();
        textNomeClienteDesmarcarConsultas = new javax.swing.JTextField();
        labeldataNascClienteDesmarcarConsultas = new javax.swing.JLabel();
        textDataNcClienteDesmarcarConsultas = new javax.swing.JTextField();
        labelNomeAnimalDesmarcarConsultas = new javax.swing.JLabel();
        textNomeAnimalDesmarcarConsultas = new javax.swing.JTextField();
        labelDataConsultaDesmarcarConsultas = new javax.swing.JLabel();
        TextDataConsultaDesmarcarConsultas = new javax.swing.JTextField();
        botaoDesmarcarConsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Desmarcar Consultas");

        labelNomeVetDesmarcarConsultas.setText("Nome do Veterinario:");

        labelNomeClienteDesmarcarConsultas.setText("Nome do Cliente:");

        labeldataNascClienteDesmarcarConsultas.setText("Data de Nascimento:");

        labelNomeAnimalDesmarcarConsultas.setText("Nome do Animal:");

        textNomeAnimalDesmarcarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeAnimalDesmarcarConsultasActionPerformed(evt);
            }
        });

        labelDataConsultaDesmarcarConsultas.setText("Data da Consulta:");

        botaoDesmarcarConsultas.setText("Cancelar Consulta");
        botaoDesmarcarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDesmarcarConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomeClienteDesmarcarConsultas)
                                .addGap(18, 18, 18)
                                .addComponent(textNomeClienteDesmarcarConsultas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labeldataNascClienteDesmarcarConsultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDataNcClienteDesmarcarConsultas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomeVetDesmarcarConsultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNomeVetDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomeAnimalDesmarcarConsultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNomeAnimalDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDataConsultaDesmarcarConsultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextDataConsultaDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoDesmarcarConsultas)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeVetDesmarcarConsultas)
                    .addComponent(textNomeVetDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeClienteDesmarcarConsultas)
                    .addComponent(textNomeClienteDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldataNascClienteDesmarcarConsultas)
                    .addComponent(textDataNcClienteDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAnimalDesmarcarConsultas)
                    .addComponent(textNomeAnimalDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataConsultaDesmarcarConsultas)
                    .addComponent(TextDataConsultaDesmarcarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(botaoDesmarcarConsultas))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeAnimalDesmarcarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeAnimalDesmarcarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeAnimalDesmarcarConsultasActionPerformed

    private void botaoDesmarcarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDesmarcarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDesmarcarConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesmarcarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesmarcarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesmarcarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesmarcarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesmarcarConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDataConsultaDesmarcarConsultas;
    private javax.swing.JButton botaoDesmarcarConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDataConsultaDesmarcarConsultas;
    private javax.swing.JLabel labelNomeAnimalDesmarcarConsultas;
    private javax.swing.JLabel labelNomeClienteDesmarcarConsultas;
    private javax.swing.JLabel labelNomeVetDesmarcarConsultas;
    private javax.swing.JLabel labeldataNascClienteDesmarcarConsultas;
    private javax.swing.JTextField textDataNcClienteDesmarcarConsultas;
    private javax.swing.JTextField textNomeAnimalDesmarcarConsultas;
    private javax.swing.JTextField textNomeClienteDesmarcarConsultas;
    private javax.swing.JTextField textNomeVetDesmarcarConsultas;
    // End of variables declaration//GEN-END:variables
}
