/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiFachadaRecepcionista;

/**
 *
 * @author alvanirjunior
 */
public class MarcarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form MarcarConsulta
     */
    public MarcarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNomeVetAgendarConsultas = new javax.swing.JLabel();
        textNomeVetAgendarConsultas = new javax.swing.JTextField();
        labelNomeClienteAgendarConsultas = new javax.swing.JLabel();
        textNomeClienteAgendarConsultas = new javax.swing.JTextField();
        labeldataNascClienteAgendarConsultas = new javax.swing.JLabel();
        textDataNcClienteAgendarConsultas = new javax.swing.JTextField();
        labelNomeAnimalAgendarConsultas = new javax.swing.JLabel();
        textNomeAnimalAgendarConsultas = new javax.swing.JTextField();
        labelDataConsultaAgendarConsultas = new javax.swing.JLabel();
        TextDataConsultaAgendarconsultas = new javax.swing.JTextField();
        botaoAgendarConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Agendar Consultas");

        labelNomeVetAgendarConsultas.setText("Nome do Veterinario:");

        labelNomeClienteAgendarConsultas.setText("Nome do Cliente:");

        labeldataNascClienteAgendarConsultas.setText("Data de Nascimento:");

        labelNomeAnimalAgendarConsultas.setText("Nome do Animal:");

        textNomeAnimalAgendarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeAnimalAgendarConsultasActionPerformed(evt);
            }
        });

        labelDataConsultaAgendarConsultas.setText("Data da Consulta:");

        TextDataConsultaAgendarconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataConsultaAgendarconsultasActionPerformed(evt);
            }
        });

        botaoAgendarConsulta.setText("Agendar Consulta");
        botaoAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNomeAnimalAgendarConsultas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNomeAnimalAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labeldataNascClienteAgendarConsultas)
                                            .addGap(18, 18, 18)
                                            .addComponent(textDataNcClienteAgendarConsultas))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelNomeClienteAgendarConsultas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textNomeClienteAgendarConsultas))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelNomeVetAgendarConsultas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textNomeVetAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDataConsultaAgendarConsultas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextDataConsultaAgendarconsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAgendarConsulta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeVetAgendarConsultas)
                    .addComponent(textNomeVetAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeClienteAgendarConsultas)
                    .addComponent(textNomeClienteAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldataNascClienteAgendarConsultas)
                    .addComponent(textDataNcClienteAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAnimalAgendarConsultas)
                    .addComponent(textNomeAnimalAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataConsultaAgendarConsultas)
                    .addComponent(TextDataConsultaAgendarconsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(botaoAgendarConsulta))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendarConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAgendarConsultaActionPerformed

    private void textNomeAnimalAgendarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeAnimalAgendarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeAnimalAgendarConsultasActionPerformed

    private void TextDataConsultaAgendarconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataConsultaAgendarconsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataConsultaAgendarconsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDataConsultaAgendarconsultas;
    private javax.swing.JButton botaoAgendarConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDataConsultaAgendarConsultas;
    private javax.swing.JLabel labelNomeAnimalAgendarConsultas;
    private javax.swing.JLabel labelNomeClienteAgendarConsultas;
    private javax.swing.JLabel labelNomeVetAgendarConsultas;
    private javax.swing.JLabel labeldataNascClienteAgendarConsultas;
    private javax.swing.JTextField textDataNcClienteAgendarConsultas;
    private javax.swing.JTextField textNomeAnimalAgendarConsultas;
    private javax.swing.JTextField textNomeClienteAgendarConsultas;
    private javax.swing.JTextField textNomeVetAgendarConsultas;
    // End of variables declaration//GEN-END:variables
}
