/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.veterinario;

/**
 *
 * @author alvanirjunior
 */
public class CadastrarRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarRecepcionista
     */
    public CadastrarRecepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastroClient = new javax.swing.JLabel();
        labelCadastroRecepcionista = new javax.swing.JLabel();
        textNomeCadastroRecepcionista = new javax.swing.JTextField();
        labelSexoCadastroRecepcionista = new javax.swing.JLabel();
        checkboxMCadastroRecepcionista = new javax.swing.JCheckBox();
        checkboxFCadastroRecepcionista = new javax.swing.JCheckBox();
        labelFoneCadastroRecepcionista = new javax.swing.JLabel();
        TextFoneCadastroRecepcionista = new javax.swing.JTextField();
        labelDataNcCadastroRecepcionista = new javax.swing.JLabel();
        textDataNsCadastroRecepcionista = new javax.swing.JTextField();
        labelEnderecoCadastroRecepcionista = new javax.swing.JLabel();
        textEnderecoCadastroRecepcionista = new javax.swing.JTextField();
        labelLoginCadastroRecepcionista = new javax.swing.JLabel();
        textLoginCadastroRecepcionista = new javax.swing.JTextField();
        labelSenhaCadastroRecepcionista = new javax.swing.JLabel();
        jPasswordField1SenhaCadastroRecepcionista = new javax.swing.JPasswordField();
        botaoCadastrarRecepcionista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCadastroClient.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        labelCadastroClient.setText("Cadastro Recepcionista");

        labelCadastroRecepcionista.setText("Nome:");

        labelSexoCadastroRecepcionista.setText("Sexo:");

        checkboxMCadastroRecepcionista.setText("Masculino");
        checkboxMCadastroRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMCadastroRecepcionistaActionPerformed(evt);
            }
        });

        checkboxFCadastroRecepcionista.setText("Feminino");

        labelFoneCadastroRecepcionista.setText("Fone:");

        labelDataNcCadastroRecepcionista.setText("Data Nascimento:");

        labelEnderecoCadastroRecepcionista.setText("Endereço:");

        labelLoginCadastroRecepcionista.setText("Login:");

        labelSenhaCadastroRecepcionista.setText("Senha:");

        jPasswordField1SenhaCadastroRecepcionista.setText("jPasswordField1");
        jPasswordField1SenhaCadastroRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1SenhaCadastroRecepcionistaActionPerformed(evt);
            }
        });

        botaoCadastrarRecepcionista.setText("Cadastrar Recepcionista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoCadastrarRecepcionista)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelLoginCadastroRecepcionista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textLoginCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSenhaCadastroRecepcionista)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1SenhaCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelEnderecoCadastroRecepcionista)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textEnderecoCadastroRecepcionista))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelCadastroRecepcionista)
                                        .addComponent(labelSexoCadastroRecepcionista)
                                        .addComponent(labelFoneCadastroRecepcionista))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textNomeCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(checkboxMCadastroRecepcionista)
                                            .addGap(18, 18, 18)
                                            .addComponent(checkboxFCadastroRecepcionista))
                                        .addComponent(TextFoneCadastroRecepcionista)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDataNcCadastroRecepcionista)
                                    .addGap(18, 18, 18)
                                    .addComponent(textDataNsCadastroRecepcionista))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelCadastroClient)
                                    .addGap(15, 15, 15))))
                        .addGap(34, 34, 34)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroClient)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCadastroRecepcionista)
                    .addComponent(textNomeCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexoCadastroRecepcionista)
                    .addComponent(checkboxMCadastroRecepcionista)
                    .addComponent(checkboxFCadastroRecepcionista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFoneCadastroRecepcionista)
                    .addComponent(TextFoneCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNcCadastroRecepcionista)
                    .addComponent(textDataNsCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnderecoCadastroRecepcionista)
                    .addComponent(textEnderecoCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLoginCadastroRecepcionista)
                    .addComponent(textLoginCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaCadastroRecepcionista)
                    .addComponent(jPasswordField1SenhaCadastroRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botaoCadastrarRecepcionista)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxMCadastroRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMCadastroRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxMCadastroRecepcionistaActionPerformed

    private void jPasswordField1SenhaCadastroRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1SenhaCadastroRecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1SenhaCadastroRecepcionistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFoneCadastroRecepcionista;
    private javax.swing.JButton botaoCadastrarRecepcionista;
    private javax.swing.JCheckBox checkboxFCadastroRecepcionista;
    private javax.swing.JCheckBox checkboxMCadastroRecepcionista;
    private javax.swing.JPasswordField jPasswordField1SenhaCadastroRecepcionista;
    private javax.swing.JLabel labelCadastroClient;
    private javax.swing.JLabel labelCadastroRecepcionista;
    private javax.swing.JLabel labelDataNcCadastroRecepcionista;
    private javax.swing.JLabel labelEnderecoCadastroRecepcionista;
    private javax.swing.JLabel labelFoneCadastroRecepcionista;
    private javax.swing.JLabel labelLoginCadastroRecepcionista;
    private javax.swing.JLabel labelSenhaCadastroRecepcionista;
    private javax.swing.JLabel labelSexoCadastroRecepcionista;
    private javax.swing.JTextField textDataNsCadastroRecepcionista;
    private javax.swing.JTextField textEnderecoCadastroRecepcionista;
    private javax.swing.JTextField textLoginCadastroRecepcionista;
    private javax.swing.JTextField textNomeCadastroRecepcionista;
    // End of variables declaration//GEN-END:variables
}
