/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.recepcionista;

import fachada.FachadaRecepcionista;
import gui.TelaMensagem;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.excecoes.AnimalJaCadastradoException;
import negocio.excecoes.ClienteNaoCadastradoException;
import negocio.excecoes.DataInvalidaException;
import util.Datas;

/**
 *
 * @author alvanirjunior
 */
public class CadastroAnimal extends javax.swing.JFrame {
    private FachadaRecepcionista recepcionista;

    /**
     * Creates new form CadastroAnimal
     */
    public CadastroAnimal(FachadaRecepcionista rec) {
        this.recepcionista = rec;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelRacaAnimal = new javax.swing.JLabel();
        jTraca = new javax.swing.JTextField();
        labelNomeCadastroAnimalA = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        labelSexoCadastroAnimalA = new javax.swing.JLabel();
        cBmacho = new javax.swing.JCheckBox();
        cBfemea = new javax.swing.JCheckBox();
        labelEspecieCadastroAnimal = new javax.swing.JLabel();
        jTespecie = new javax.swing.JTextField();
        labelDataCadastroAnimalA = new javax.swing.JLabel();
        jTdn = new javax.swing.JTextField();
        botaoCadastrarAnimal = new javax.swing.JButton();
        botaoCadastrarAnimal1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTdnDono = new javax.swing.JTextField();
        jTnomeDono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Cadastro Animal");

        labelRacaAnimal.setText("Raça:");

        jTraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTracaActionPerformed(evt);
            }
        });

        labelNomeCadastroAnimalA.setText("Nome do Animal:");

        labelSexoCadastroAnimalA.setText("Sexo:");

        cBmacho.setText("Macho");
        cBmacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBmachoActionPerformed(evt);
            }
        });

        cBfemea.setText("Fêmea");
        cBfemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBfemeaActionPerformed(evt);
            }
        });

        labelEspecieCadastroAnimal.setText("Especie:");

        labelDataCadastroAnimalA.setText("Data de Nascimento:");

        botaoCadastrarAnimal.setText("Cadastrar Animal");
        botaoCadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarAnimalActionPerformed(evt);
            }
        });

        botaoCadastrarAnimal1.setText("Cancelar");
        botaoCadastrarAnimal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarAnimal1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Dono:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Data de nascimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCadastrarAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrarAnimal1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTdnDono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTnomeDono)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelNomeCadastroAnimalA)
                                    .addGap(24, 24, 24)
                                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(labelSexoCadastroAnimalA))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelDataCadastroAnimalA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTdn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelEspecieCadastroAnimal)
                                        .addComponent(labelRacaAnimal))
                                    .addGap(64, 64, 64)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTraca, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jTespecie))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cBfemea)
                                .addComponent(cBmacho)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCadastroAnimalA)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSexoCadastroAnimalA)
                    .addComponent(cBmacho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDataCadastroAnimalA)
                        .addComponent(jTdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cBfemea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEspecieCadastroAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRacaAnimal)
                    .addComponent(jTraca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(jTnomeDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTdnDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarAnimal)
                    .addComponent(botaoCadastrarAnimal1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTracaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTracaActionPerformed

    private void cBmachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBmachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBmachoActionPerformed

    private void cBfemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBfemeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBfemeaActionPerformed

    private void botaoCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarAnimalActionPerformed
        String sexo = "";

        if (this.cBfemea.isSelected()) {
            sexo = "Femea";
        } else if (this.cBmacho.isSelected()) {
            sexo = "Macho";
        }
        if (!this.jTnome.getText().equals("") && !this.jTnomeDono.equals("") && !this.jTraca.getText().equals("") && !this.jTespecie.equals("")) {
            if (!sexo.equals("")) {
                try {
                    this.recepcionista.cadastrarAnimal(this.jTnomeDono.getText(), Datas.getData(this.jTdnDono.getText()), jTnome.getText(), sexo, jTespecie.getText(), jTraca.getText(), Datas.getData(jTdn.getText()));
                    MenuRecepcionista tela = new MenuRecepcionista(recepcionista);
                    tela.setVisible(true);
                    this.dispose();                    
                    new TelaMensagem("Cadastro efetuado").setVisible(true);
                } catch (DataInvalidaException | ClienteNaoCadastradoException | AnimalJaCadastradoException ex) {
                    new TelaMensagem(ex.getMessage()).setVisible(true);
                }
            } else {
                new TelaMensagem("Selecione o sexo!").setVisible(true);
            }

        }else
            new TelaMensagem("Preencha todos os campos").setVisible(true);

    }//GEN-LAST:event_botaoCadastrarAnimalActionPerformed

    private void botaoCadastrarAnimal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarAnimal1ActionPerformed
        MenuRecepcionista tela = new MenuRecepcionista(recepcionista);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCadastrarAnimal1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarAnimal;
    private javax.swing.JButton botaoCadastrarAnimal1;
    private javax.swing.JCheckBox cBfemea;
    private javax.swing.JCheckBox cBmacho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTdn;
    private javax.swing.JTextField jTdnDono;
    private javax.swing.JTextField jTespecie;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTnomeDono;
    private javax.swing.JTextField jTraca;
    private javax.swing.JLabel labelDataCadastroAnimalA;
    private javax.swing.JLabel labelEspecieCadastroAnimal;
    private javax.swing.JLabel labelNomeCadastroAnimalA;
    private javax.swing.JLabel labelRacaAnimal;
    private javax.swing.JLabel labelSexoCadastroAnimalA;
    // End of variables declaration//GEN-END:variables
}
