/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.recepcionista;

/**
 *
 * @author alvanirjunior
 */
public class CadastroAnimal extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAnimal
     */
    public CadastroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelRacaAnimal = new javax.swing.JLabel();
        textRacaAnimal = new javax.swing.JTextField();
        labelNomeCadastroAnimalA = new javax.swing.JLabel();
        textNomeCadastroAnimalA = new javax.swing.JTextField();
        labelSexoCadastroAnimalA = new javax.swing.JLabel();
        checkboxMCadastroAnimal = new javax.swing.JCheckBox();
        checkboxFCadastroAnimal = new javax.swing.JCheckBox();
        labelEspecieCadastroAnimal = new javax.swing.JLabel();
        textEspecieCadastroAnimal = new javax.swing.JTextField();
        labelDataCadastroAnimalA = new javax.swing.JLabel();
        textDataCadastroAnimalA = new javax.swing.JTextField();
        botaoCadastrarAnimal = new javax.swing.JButton();
        botaoCadastrarAnimal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Cadastro Animal");

        labelRacaAnimal.setText("Raça:");

        textRacaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRacaAnimalActionPerformed(evt);
            }
        });

        labelNomeCadastroAnimalA.setText("Nome do Animal:");

        labelSexoCadastroAnimalA.setText("Sexo:");

        checkboxMCadastroAnimal.setText("Macho");
        checkboxMCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxMCadastroAnimalActionPerformed(evt);
            }
        });

        checkboxFCadastroAnimal.setText("Fêmea");
        checkboxFCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxFCadastroAnimalActionPerformed(evt);
            }
        });

        labelEspecieCadastroAnimal.setText("Especie:");

        labelDataCadastroAnimalA.setText("Data de Nascimento:");

        botaoCadastrarAnimal.setText("Cadastrar Animal");
        botaoCadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarAnimalActionPerformed(evt);
            }
        });

        botaoCadastrarAnimal1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomeCadastroAnimalA)
                                .addGap(24, 24, 24)
                                .addComponent(textNomeCadastroAnimalA, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDataCadastroAnimalA)
                                    .addComponent(labelEspecieCadastroAnimal)
                                    .addComponent(labelRacaAnimal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textRacaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textEspecieCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(textDataCadastroAnimalA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelSexoCadastroAnimalA)
                                            .addGap(18, 18, 18)
                                            .addComponent(checkboxMCadastroAnimal)
                                            .addGap(31, 31, 31)
                                            .addComponent(checkboxFCadastroAnimal)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoCadastrarAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrarAnimal1)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCadastroAnimalA)
                    .addComponent(textNomeCadastroAnimalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataCadastroAnimalA)
                    .addComponent(textDataCadastroAnimalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSexoCadastroAnimalA)
                    .addComponent(checkboxMCadastroAnimal)
                    .addComponent(checkboxFCadastroAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEspecieCadastroAnimal)
                    .addComponent(textEspecieCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRacaAnimal)
                    .addComponent(textRacaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarAnimal)
                    .addComponent(botaoCadastrarAnimal1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textRacaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRacaAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRacaAnimalActionPerformed

    private void checkboxMCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxMCadastroAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxMCadastroAnimalActionPerformed

    private void checkboxFCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxFCadastroAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxFCadastroAnimalActionPerformed

    private void botaoCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarAnimalActionPerformed
        
    }//GEN-LAST:event_botaoCadastrarAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarAnimal;
    private javax.swing.JButton botaoCadastrarAnimal1;
    private javax.swing.JCheckBox checkboxFCadastroAnimal;
    private javax.swing.JCheckBox checkboxMCadastroAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDataCadastroAnimalA;
    private javax.swing.JLabel labelEspecieCadastroAnimal;
    private javax.swing.JLabel labelNomeCadastroAnimalA;
    private javax.swing.JLabel labelRacaAnimal;
    private javax.swing.JLabel labelSexoCadastroAnimalA;
    private javax.swing.JTextField textDataCadastroAnimalA;
    private javax.swing.JTextField textEspecieCadastroAnimal;
    private javax.swing.JTextField textNomeCadastroAnimalA;
    private javax.swing.JTextField textRacaAnimal;
    // End of variables declaration//GEN-END:variables
}
