/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.recepcionista;

import fachada.FachadaRecepcionista;
import gui.TelaMensagem;
import negocio.excecoes.ClienteNaoCadastradoException;
import negocio.excecoes.DataInvalidaException;
import util.Datas;

/**
 *
 * @author alvanirjunior
 */
public class ConsultarCadastroCliente extends javax.swing.JFrame {
    private FachadaRecepcionista recepcionista;
    /**
     * Creates new form ConsultarCadastroCliente
     */
    public ConsultarCadastroCliente(FachadaRecepcionista recepcionista) {
        initComponents();
        this.recepcionista = recepcionista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeClienteConsultarCadastroCliente = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        labelDataConsultarCadastroCliente = new javax.swing.JLabel();
        jTdata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botaoConsultarCadastroCliente = new javax.swing.JButton();
        botaoConsultarCadastroCliente1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomeClienteConsultarCadastroCliente.setText("Nome do Cliente:");

        labelDataConsultarCadastroCliente.setText("Data de nascimento:");

        jTdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Consultar Cadastro Cliente");

        botaoConsultarCadastroCliente.setText("Consultar Cadastro");
        botaoConsultarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarCadastroClienteActionPerformed(evt);
            }
        });

        botaoConsultarCadastroCliente1.setText("Cancelar");
        botaoConsultarCadastroCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarCadastroCliente1ActionPerformed(evt);
            }
        });

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomeClienteConsultarCadastroCliente)
                            .addComponent(labelDataConsultarCadastroCliente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(botaoConsultarCadastroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoConsultarCadastroCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeClienteConsultarCadastroCliente)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataConsultarCadastroCliente)
                    .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConsultarCadastroCliente)
                    .addComponent(botaoConsultarCadastroCliente1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdataActionPerformed

    private void botaoConsultarCadastroCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarCadastroCliente1ActionPerformed
        MenuRecepcionista menu = new MenuRecepcionista(recepcionista);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoConsultarCadastroCliente1ActionPerformed

    private void botaoConsultarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarCadastroClienteActionPerformed
        try {
            String s = this.recepcionista.consultarCadastroCliente(this.jTnome.getText(), Datas.getData(jTdata.getText()));
            InformacoesCliente janela = new InformacoesCliente(this.recepcionista, this.jTnome.getText(), this.jTdata.getText(), s);
            janela.setVisible(true);
            this.dispose();
        } catch (DataInvalidaException | ClienteNaoCadastradoException ex) {
            TelaMensagem tela = new TelaMensagem(ex.getMessage());
        }
    }//GEN-LAST:event_botaoConsultarCadastroClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListaClientes tela = new ListaClientes(recepcionista);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConsultarCadastroCliente;
    private javax.swing.JButton botaoConsultarCadastroCliente1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTdata;
    private javax.swing.JTextField jTnome;
    private javax.swing.JLabel labelDataConsultarCadastroCliente;
    private javax.swing.JLabel labelNomeClienteConsultarCadastroCliente;
    // End of variables declaration//GEN-END:variables
}
