/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.recepcionista;

import fachada.FachadaRecepcionista;
import gui.TelaMensagem;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.excecoes.ClienteNaoCadastradoException;
import negocio.excecoes.DataInvalidaException;
import util.Datas;

/**
 *
 * @author Yuri
 */
public class ListaClientes extends javax.swing.JFrame {

    private FachadaRecepcionista recepcionista;

    /**
     * Creates new form ListaClientes
     */
    public ListaClientes(FachadaRecepcionista recepcionista) {
        initComponents();
        this.recepcionista = recepcionista;
        this.carregarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLclientes = new java.awt.List();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarLista(){
        this.jLclientes.removeAll();
        for(String s : this.recepcionista.consultarListaClientes())
            this.jLclientes.add(s);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuRecepcionista menu = new MenuRecepcionista(recepcionista);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(this.jLclientes.getSelectedItem() != null){
            String info;

            try {
                info = this.recepcionista.consultarCadastroCliente(getNome(), this.getData());
                InformacoesCliente tela = new InformacoesCliente(recepcionista, getNome(), getDataString(), info);
                tela.setVisible(true);
                this.dispose();
            } catch (DataInvalidaException | ClienteNaoCadastradoException ex) {
                new TelaMensagem(ex.getMessage()).setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this.jLclientes.getSelectedItem() != null) {
            try {
                this.recepcionista.removerCliente(getNome(), getData());
                this.carregarLista();
            } catch (DataInvalidaException | ClienteNaoCadastradoException ex) {
                new TelaMensagem(ex.getMessage()).setVisible(true);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private LocalDate getData() throws DataInvalidaException {
        return Datas.getData(getDataString());
    }

    private String getDataString() {
        return this.jLclientes.getSelectedItem().split(" ")[this.jLclientes.getSelectedItem().split(" ").length - 1];
    }

    
    
    private String getNome(){
        String nome = "";
        
        for(String s : this.jLclientes.getSelectedItem().split(" ")){
            if(s.equals("Data")){
                break;
            }
            if(!s.equals(""))
                nome += s+" ";
        }
        nome = nome.substring(0, nome.length() - 1);
        return nome;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private java.awt.List jLclientes;
    // End of variables declaration//GEN-END:variables
}
