/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.recepcionista;

import fachada.FachadaRecepcionista;

/**
 *
 * @author alvanirjunior
 */
public class MarcarConsulta extends javax.swing.JFrame {
    private FachadaRecepcionista recepcionista;
    /**
     * Creates new form MarcarConsulta
     */
    public MarcarConsulta(FachadaRecepcionista recepcionista) {
        initComponents();
        this.recepcionista = recepcionista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNomeVetAgendarConsultas = new javax.swing.JLabel();
        textNomeVetAgendarConsultas = new javax.swing.JTextField();
        labelNomeClienteAgendarConsultas = new javax.swing.JLabel();
        textNomeClienteAgendarConsultas = new javax.swing.JTextField();
        labeldataNascClienteAgendarConsultas = new javax.swing.JLabel();
        textDataNcClienteAgendarConsultas = new javax.swing.JTextField();
        labelNomeAnimalAgendarConsultas = new javax.swing.JLabel();
        textNomeAnimalAgendarConsultas = new javax.swing.JTextField();
        labelDataNcAnimalAgendarConsultas = new javax.swing.JLabel();
        TextDataNcAnimalAgendarconsultas = new javax.swing.JTextField();
        botaoAgendarConsulta = new javax.swing.JButton();
        botaoAgendarConsulta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel1.setText("Agendar Consultas");

        labelNomeVetAgendarConsultas.setText("Nome do Veterinario:");

        labelNomeClienteAgendarConsultas.setText("Nome do Cliente:");

        labeldataNascClienteAgendarConsultas.setText("Data de Nascimento:");

        labelNomeAnimalAgendarConsultas.setText("Nome do Animal:");

        textNomeAnimalAgendarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeAnimalAgendarConsultasActionPerformed(evt);
            }
        });

        labelDataNcAnimalAgendarConsultas.setText("Data da Consulta:");

        botaoAgendarConsulta.setText("Agendar");
        botaoAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendarConsultaActionPerformed(evt);
            }
        });

        botaoAgendarConsulta1.setText("Cancelar");
        botaoAgendarConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendarConsulta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNomeVetAgendarConsultas)
                                    .addComponent(labelNomeClienteAgendarConsultas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNomeClienteAgendarConsultas)
                                    .addComponent(textNomeVetAgendarConsultas)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(labelDataNcAnimalAgendarConsultas)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(TextDataNcAnimalAgendarconsultas))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(labeldataNascClienteAgendarConsultas)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(textDataNcClienteAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNomeAnimalAgendarConsultas)
                                                .addGap(24, 24, 24)
                                                .addComponent(textNomeAnimalAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(botaoAgendarConsulta)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAgendarConsulta1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeVetAgendarConsultas)
                    .addComponent(textNomeVetAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeClienteAgendarConsultas)
                    .addComponent(textNomeClienteAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldataNascClienteAgendarConsultas)
                    .addComponent(textDataNcClienteAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAnimalAgendarConsultas)
                    .addComponent(textNomeAnimalAgendarConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNcAnimalAgendarConsultas)
                    .addComponent(TextDataNcAnimalAgendarconsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAgendarConsulta)
                    .addComponent(botaoAgendarConsulta1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendarConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAgendarConsultaActionPerformed

    private void textNomeAnimalAgendarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeAnimalAgendarConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeAnimalAgendarConsultasActionPerformed

    private void botaoAgendarConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendarConsulta1ActionPerformed
        MenuRecepcionista menu = new MenuRecepcionista(recepcionista);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoAgendarConsulta1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDataNcAnimalAgendarconsultas;
    private javax.swing.JButton botaoAgendarConsulta;
    private javax.swing.JButton botaoAgendarConsulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDataNcAnimalAgendarConsultas;
    private javax.swing.JLabel labelNomeAnimalAgendarConsultas;
    private javax.swing.JLabel labelNomeClienteAgendarConsultas;
    private javax.swing.JLabel labelNomeVetAgendarConsultas;
    private javax.swing.JLabel labeldataNascClienteAgendarConsultas;
    private javax.swing.JTextField textDataNcClienteAgendarConsultas;
    private javax.swing.JTextField textNomeAnimalAgendarConsultas;
    private javax.swing.JTextField textNomeClienteAgendarConsultas;
    private javax.swing.JTextField textNomeVetAgendarConsultas;
    // End of variables declaration//GEN-END:variables
}
